name: estudiafacil
description: EstudiaFÃ¡cil - App educativa con IA
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^10.3.6
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_markdown_plus: ^1.0.5
  syncfusion_flutter_pdfviewer: ^31.2.10
  url_launcher: ^6.3.2
  image_picker: ^1.0.4
  connectivity_plus: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/icons/Icon-512.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#0175C2"
  adaptive_icon_foreground: "web/icons/Icon-192.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: "web/icons/Icon-192.png"
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
    icon_background_color: "#FFFFFF"
  web: true